
services:
  php:
    build:
      context: ./docker
    container_name: fv_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app_network


  database:
    image: mysql:8.0
    container_name: fv_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
